export { buildSimulatorConfig } from "./config";
export type { RawSimulatorConfig } from "./config";
export { loadSimulatorConfig, loadSimulatorConfigFromDir } from "./config-node";
export { createTroopStatsRecord, fireCrystalMultiplier, generateTroopStats, generateTroopStatsCatalogue } from "./troopStats";
export { prepareBattle } from "./prepare";
export type { CompiledBattle } from "./prepare";
export { runPrepared, simulateBattles } from "./simulator";
export { BattleInputBuilder } from "./battleInputBuilder";
export { applyHeroGenerationStats } from "./fighterResolution";
export type * from "./types";
