import { fileURLToPath } from "node:url";
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const HERO_DEFINITIONS_DIR = resolve(
  REPO_ROOT,
  "simulator/config/hero_definitions",
);
export const GENERATED_MANIFEST_PATH = resolve(
  REPO_ROOT,
  "simulator/src/generated/heroDefinitions.ts",
);

export function discoverHeroDefinitionFiles(
  definitionsDir = HERO_DEFINITIONS_DIR,
): string[] {
  return readdirSync(definitionsDir)
    .filter((name) => name.endsWith(".json"))
    .sort((a, b) => a.localeCompare(b));
}

export function generatedHeroManifestSource(
  files = discoverHeroDefinitionFiles(),
): string {
  const imports = files.map(
    (file, index) =>
      `import hero${index} from "../../config/hero_definitions/${file}" with { type: "json" };`,
  );
  const entries = files.map((file, index) => {
    const name = file.slice(0, -".json".length);
    return `  ${JSON.stringify(name)}: hero${index},`;
  });

  return [
    "// This file is generated by scripts/generate_hero_manifest.ts.",
    "// Do not edit it directly; add or remove hero definition JSON files instead.",
    "",
    ...imports,
    "",
    'import type { SkillFile } from "../types";',
    "",
    "export const DEFAULT_HERO_DEFINITIONS = {",
    ...entries,
    "} as unknown as Record<string, SkillFile>;",
    "",
  ].join("\n");
}

function main(): void {
  const expected = generatedHeroManifestSource();
  if (process.argv.includes("--check")) {
    const actual = readFileSync(GENERATED_MANIFEST_PATH, "utf8");
    if (actual !== expected) {
      const output = relative(REPO_ROOT, GENERATED_MANIFEST_PATH);
      throw new Error(
        `${output} is stale; run npx tsx scripts/generate_hero_manifest.ts`,
      );
    }
    return;
  }
  mkdirSync(dirname(GENERATED_MANIFEST_PATH), { recursive: true });
  writeFileSync(GENERATED_MANIFEST_PATH, expected);
}

if (resolve(process.argv[1] ?? "") === fileURLToPath(import.meta.url)) {
  main();
}
