CREATE ROLE wos_sim LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE wos_sim OWNER wos_sim;

REVOKE CONNECT ON DATABASE wos_sim FROM PUBLIC;
GRANT CONNECT ON DATABASE wos_sim TO wos_sim;
